# Generated by Django 5.2.5 on 2025-09-02 20:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpreendedorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Perfil Empresarial - Empreendedor',
                'verbose_name_plural': 'Perfis Empresariais - Empreendedor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts_management.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaUser',
            fields=[
            ],
            options={
                'verbose_name': 'Perfil Empresarial - Empresa',
                'verbose_name_plural': 'Perfis Empresariais - Empresa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts_management.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
