# Generated by Django 5.2.5 on 2025-09-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EmpreendedorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('biografia', models.TextField(verbose_name='Biografia / Resumo Profissional')),
                ('area_atuacao', models.CharField(max_length=150, verbose_name='Área de Atuação')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp para Contato')),
                ('rede_social_profissional', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link para Rede Social Profissional (LinkedIn, etc.)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empreendedor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('telefone_institucional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Institucional')),
                ('email_institucional', models.EmailField(max_length=255, verbose_name='E-mail Institucional')),
                ('responsavel_nome', models.CharField(max_length=255, verbose_name='Nome Completo do Responsável')),
                ('responsavel_email', models.EmailField(max_length=255, verbose_name='E-mail do Responsável')),
                ('responsavel_telefone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp do Responsável')),
                ('responsavel_cargo', models.CharField(max_length=100, verbose_name='Cargo/Função do Responsável')),
                ('logotipo', models.ImageField(upload_to='logotipos/', verbose_name='Logotipo')),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('redes_sociais', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redes Sociais (links separados por vírgula)')),
                ('comprovante_dados', models.FileField(upload_to='comprovantes/empresa/', verbose_name='Comprovante de Dados Empresariais (PDF, JPG)')),
                ('comprovante_responsavel', models.FileField(upload_to='comprovantes/responsavel/', verbose_name='Comprovante do Responsável Legal (PDF, JPG)')),
                ('cnae_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_principal', to='profiles_management.cnae', verbose_name='CNAE Principal')),
                ('cnaes_secundarios', models.ManyToManyField(blank=True, related_name='empresas_secundarias', to='profiles_management.cnae', verbose_name='CNAEs Secundários')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
