# Generated by Django 5.2.5 on 2025-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaprofile',
            name='inscricao_estadual',
            field=models.CharField(default='', max_length=20, verbose_name='Inscrição Estadual'),
            preserve_default=False,
        ),
    ]
