# Generated by Django 5.2.5 on 2025-09-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoInteligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DADOS_ESTRUTURAIS', 'Dados Estruturais'), ('ANALISES_E_ARTIGOS', 'Análises e Artigos')], max_length=50, verbose_name='Categoria')),
                ('titulo_card', models.CharField(help_text='Título que aparece na listagem de cards.', max_length=100, verbose_name='Título do Card')),
                ('imagem_card', models.ImageField(help_text='Imagem de capa que aparece na listagem.', upload_to='intelligence/cards/', verbose_name='Imagem do Card')),
                ('titulo_interno', models.CharField(help_text='Título principal exibido dentro da página do conteúdo.', max_length=200, verbose_name='Título do Conteúdo')),
                ('subtitulo', models.CharField(blank=True, help_text='Texto curto que aparece abaixo do título principal.', max_length=300, null=True, verbose_name='Subtítulo')),
                ('corpo_texto', models.TextField(help_text='O conteúdo principal do artigo. Use [grafico:sua-chave] para inserir um gráfico.', verbose_name='Corpo do Conteúdo')),
            ],
            options={
                'verbose_name': 'Conteúdo de Inteligência',
                'verbose_name_plural': '2. Conteúdos de Inteligência',
                'ordering': ['categoria', 'titulo_card'],
            },
        ),
        migrations.CreateModel(
            name='GraficoECharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título interno para identificar o gráfico no painel de administração.', max_length=200, unique=True)),
                ('chave', models.SlugField(blank=True, help_text='Chave de texto única gerada automaticamente para usar no texto (ex: [grafico:minha-chave]).', max_length=220, unique=True)),
                ('codigo_js', models.TextField(help_text="Cole aqui o código JavaScript da 'option' do seu gráfico ECharts.", verbose_name='Código JavaScript do Gráfico')),
            ],
            options={
                'verbose_name': 'Gráfico ECharts',
                'verbose_name_plural': '1. Gráficos ECharts',
            },
        ),
    ]
