# Generated by Django 5.2.5 on 2025-09-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_intelligence_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossarioTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100, unique=True, verbose_name='Termo')),
                ('explicacao', models.TextField(help_text='Use as ferramentas de formatação para criar uma explicação clara.', verbose_name='Explicação')),
            ],
            options={
                'verbose_name': 'Termo do Glossário',
                'verbose_name_plural': '3. Glossário de Termos',
                'ordering': ['termo'],
            },
        ),
        migrations.AlterModelOptions(
            name='conteudointeligencia',
            options={'ordering': ['categoria', 'titulo_card'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterModelOptions(
            name='graficoecharts',
            options={'verbose_name': 'Gráfico', 'verbose_name_plural': 'Gráficos'},
        ),
    ]
