# Generated by Django 5.2.5 on 2025-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Logo que aparece no header.', upload_to='logos/header/')),
                ('link', models.URLField(blank=True, help_text='Link opcional para o logo.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagem principal da home page.', upload_to='hero_images/')),
                ('link', models.URLField(blank=True, help_text='Link opcional para a imagem.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Use 0, 1, 2... para definir a ordem de aparição.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Logo dos parceiros no rodapé.', upload_to='logos/partners/')),
                ('link', models.URLField(blank=True, help_text='Link opcional para o parceiro.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Use 0, 1, 2... para definir a ordem no carrossel.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]